---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: dev
  url: https://github.com//work-out-app

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: work-out-app-dev
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: work-out-app-dev
